# Generated by Django 5.2.5 on 2025-08-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_filiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filiere',
        ),
    ]
