# Generated by Django 5.2.5 on 2025-08-21 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='schoollevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.schoollevel'),
        ),
    ]
