# Generated by Django 5.2.5 on 2025-08-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_studentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_cnt', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('correct_cnt', models.IntegerField(default=0)),
                ('incorrect_cnt', models.IntegerField(default=0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prereqs', models.ManyToManyField(blank=True, related_name='unlocks', to='quiz_app.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mastery', models.FloatField(default=0.2)),
                ('unlocked', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topic')),
            ],
        ),
    ]
