# Generated by Django 5.2.5 on 2025-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnertopic',
            name='unlocked',
            field=models.BooleanField(default=True),
        ),
    ]
