# Generated by Django 5.2.5 on 2025-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_alter_learnertopic_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='explanation_shown',
            field=models.BooleanField(default=False),
        ),
    ]
